version: '3.5'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  weather_api:
    container_name: weather_api
    build:
      context: ./WeatherApp
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=postgres_db;port=5432;user id=postgres;password=example;database=Weather;
    ports:
      - "5030:80"

volumes:
  postgres: