apiVersion: v1
kind: Service
metadata:
  name: postgres-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres-db #lable of the template in deployment file
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP