apiVersion: v1
kind: Service
metadata:
  name: weather-api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: weather-api #lable of the template in deployment file
  ports:
    - port: 3051
      targetPort: 80