apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-pod
  labels:
    component: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "example"